default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: cs3710_fall_2025_001_assignment_02_development

test:
  <<: *default
  database: cs3710_fall_2025_001_assignment_02_test

production:
  <<: *default
  database: cs3710_fall_2025_001_assignment_02_production
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || "postgres" %>
